# # 53_IT_Vendra [GUI registration form]
# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'practicalregform3.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.4
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
# import mysql.connector.connection
# import mysql.connector
# import mysql
# from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtWidgets import QMessageBox
#
#
# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(800, 600)
#         MainWindow.setStyleSheet("background-color: rgb(168, 139, 235);\n"
# "background-color: rgb(74, 74, 74);")
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.label = QtWidgets.QLabel(self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(110, 30, 591, 41))
#         self.label.setStyleSheet("color:rgb(168, 139, 235);font-size:28pt;")
#         self.label.setObjectName("label")
#         self.label_2 = QtWidgets.QLabel(self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(40, 130, 101, 41))
#         self.label_2.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;")
#         self.label_2.setObjectName("label_2")
#         self.label_3 = QtWidgets.QLabel(self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(230, 190, 161, 31))
#         self.label_3.setStyleSheet("color:rgb(168, 139, 235);font-size:15pt;")
#         self.label_3.setObjectName("label_3")
#         self.label_4 = QtWidgets.QLabel(self.centralwidget)
#         self.label_4.setGeometry(QtCore.QRect(590, 190, 151, 31))
#         self.label_4.setStyleSheet("color:rgb(168, 139, 235);font-size:15pt;")
#         self.label_4.setObjectName("label_4")
#         self.label_5 = QtWidgets.QLabel(self.centralwidget)
#         self.label_5.setGeometry(QtCore.QRect(390, 190, 191, 31))
#         self.label_5.setStyleSheet("color:rgb(168, 139, 235);font-size:15pt;")
#         self.label_5.setObjectName("label_5")
#         self.label_6 = QtWidgets.QLabel(self.centralwidget)
#         self.label_6.setGeometry(QtCore.QRect(40, 240, 131, 31))
#         self.label_6.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;")
#         self.label_6.setObjectName("label_6")
#         self.label_7 = QtWidgets.QLabel(self.centralwidget)
#         self.label_7.setGeometry(QtCore.QRect(40, 320, 141, 31))
#         self.label_7.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;")
#         self.label_7.setObjectName("label_7")
#         self.label_8 = QtWidgets.QLabel(self.centralwidget)
#         self.label_8.setGeometry(QtCore.QRect(40, 400, 141, 31))
#         self.label_8.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;")
#         self.label_8.setObjectName("label_8")
#         self.firstname = QtWidgets.QLineEdit(self.centralwidget)
#         self.firstname.setGeometry(QtCore.QRect(220, 130, 161, 41))
#         self.firstname.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
#         self.firstname.setText("")
#         self.firstname.setObjectName("firstname")
#         self.middlename = QtWidgets.QLineEdit(self.centralwidget)
#         self.middlename.setGeometry(QtCore.QRect(402, 130, 161, 41))
#         self.middlename.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
#         self.middlename.setObjectName("middlename")
#         self.lastname = QtWidgets.QLineEdit(self.centralwidget)
#         self.lastname.setGeometry(QtCore.QRect(582, 130, 151, 41))
#         self.lastname.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
#         self.lastname.setObjectName("lastname")
#         self.emailid = QtWidgets.QLineEdit(self.centralwidget)
#         self.emailid.setGeometry(QtCore.QRect(220, 240, 511, 41))
#         self.emailid.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);\n"
# "")
#         self.emailid.setObjectName("emailid")
#         self.phoneno = QtWidgets.QLineEdit(self.centralwidget)
#         self.phoneno.setGeometry(QtCore.QRect(220, 320, 511, 41))
#         self.phoneno.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
#         self.phoneno.setObjectName("phoneno")
#         self.pushButton = QtWidgets.QPushButton(self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(320, 480, 151, 51))
#         self.pushButton.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;\n"
# "background-color: rgb(225, 225, 225);\n"
# "")
#         self.pushButton.setObjectName("pushButton")
#         self.pushButton.clicked.connect(self.register)
#         self.password = QtWidgets.QLineEdit(self.centralwidget)
#         self.password.setGeometry(QtCore.QRect(220, 390, 511, 41))
#         self.password.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
#         self.password.setObjectName("password")
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.label.setText(_translate("MainWindow", "USER REGISTRATION FORM"))
#         self.label_2.setText(_translate("MainWindow", "Name"))
#         self.label_3.setText(_translate("MainWindow", "First Name"))
#         self.label_4.setText(_translate("MainWindow", "Last Name"))
#         self.label_5.setText(_translate("MainWindow", "Middle Name"))
#         self.label_6.setText(_translate("MainWindow", "Email ID"))
#         self.label_7.setText(_translate("MainWindow", "Phone no"))
#         self.label_8.setText(_translate("MainWindow", "Password"))
#         self.pushButton.setText(_translate("MainWindow", "Register"))
#
#
#     def register(self):
#         firstname = str(self.firstname.text())
#         middlename = str(self.middlename.text())
#         lastname = str(self.lastname.text())
#         emailid = str(self.emailid.text())
#         phoneno = str(self.phoneno.text())
#         password = str(self.password.text())
#         try:
#             mydb = mysql.connector.connect(
#                 host="localhost",
#                 user="root",
#                 password="",
#                 database="userregistration"
#             )
#
#             mycursor = mydb.cursor()
#
#             sql = "INSERT INTO userdetails (firstname, middlename, lastname, emailid, phoneno, password) VALUES (%s, %s, %s, %s, %s, %s)"
#             val = (firstname, middlename, lastname, emailid, phoneno, password)
#             mycursor.execute(sql, val)
#
#             mydb.commit()
#             mydb.close()
#             self.successful()
#             print("Database Connected Successfully!")
#         except:
#             # print("Error")
#             self.error("Database Connection Failed!")
#
#     def successful(self):
#         msg = QMessageBox()
#         msg.setIcon(QMessageBox.Information)
#         msg.setText("The User Data Is Registered Successfully!")
#         msg.setStandardButtons(QMessageBox.Save)
#         msg.exec_()
#
#     def error(self, message):
#         msg = QMessageBox()
#         msg.setIcon(QMessageBox.Critical)
#         msg.setText(message)
#         msg.setStandardButtons(QMessageBox.Ok)
#         msg.exec_()
#
#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practicalregform3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import mysql
import mysql.connector.connection
import win32gui
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import database2


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(168, 139, 235);\n"
"background-color: rgb(74, 74, 74);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 591, 41))
        self.label.setStyleSheet("color:rgb(168, 139, 235);font-size:28pt;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 101, 41))
        self.label_2.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 190, 161, 31))
        self.label_3.setStyleSheet("color:rgb(168, 139, 235);font-size:15pt;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(590, 190, 151, 31))
        self.label_4.setStyleSheet("color:rgb(168, 139, 235);font-size:15pt;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 190, 191, 31))
        self.label_5.setStyleSheet("color:rgb(168, 139, 235);font-size:15pt;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 131, 31))
        self.label_6.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 320, 141, 31))
        self.label_7.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;")
        self.label_7.setObjectName("label_7")
        self.firstname = QtWidgets.QLineEdit(self.centralwidget)
        self.firstname.setGeometry(QtCore.QRect(220, 130, 161, 41))
        self.firstname.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
        self.firstname.setText("")
        self.firstname.setObjectName("firstname")
        self.middlename = QtWidgets.QLineEdit(self.centralwidget)
        self.middlename.setGeometry(QtCore.QRect(402, 130, 161, 41))
        self.middlename.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
        self.middlename.setObjectName("middlename")
        self.lastname = QtWidgets.QLineEdit(self.centralwidget)
        self.lastname.setGeometry(QtCore.QRect(582, 130, 151, 41))
        self.lastname.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
        self.lastname.setObjectName("lastname")
        self.emailid = QtWidgets.QLineEdit(self.centralwidget)
        self.emailid.setGeometry(QtCore.QRect(220, 240, 511, 41))
        self.emailid.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);\n"
"")
        self.emailid.setObjectName("emailid")
        self.phoneno = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneno.setGeometry(QtCore.QRect(220, 320, 511, 41))
        self.phoneno.setStyleSheet("font-size:15pt;color:rgb(253, 169, 253);")
        self.phoneno.setObjectName("phoneno")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 410, 151, 51))
        self.pushButton.setStyleSheet("color:rgb(168, 139, 235);font-size:20pt;\n"
"background-color: rgb(225, 225, 225);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.register)
        # self.connectToDatabase = QtWidgets.QPushButton(self.centralwidget)
#         self.connectToDatabase.setGeometry(QtCore.QRect(522, 480, 221, 31))
#         self.connectToDatabase.setStyleSheet("font-size:12pt;\n"
# "color:rgb(168, 139, 235);\n"
# "background-color: rgb(225, 225, 225);")
        # self.connectToDatabase.setObjectName("connectToDatabase")
        # self.pushButton.clicked.connect(self.secondwindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "USER REGISTRATION FORM"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Last Name"))
        self.label_5.setText(_translate("MainWindow", "Middle Name"))
        self.label_6.setText(_translate("MainWindow", "Email ID"))
        self.label_7.setText(_translate("MainWindow", "Phone no"))
        self.pushButton.setText(_translate("MainWindow", "Register"))
        # self.connectToDatabase.setText(_translate("MainWindow", "List of registered users"))

    def secondwindow(self):
        database2

    def register(self):


        firstname = str(self.firstname.text())
        middlename = str(self.middlename.text())
        lastname = str(self.lastname.text())
        emailid = str(self.emailid.text())
        phoneno = str(self.phoneno.text())
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="userregistration"
            )

            mycursor = mydb.cursor()

            sql = "INSERT INTO userdetails (firstname, middlename, lastname, emailid, phoneno) VALUES (%s, %s, %s, %s, %s)"
            val = (firstname, middlename, lastname, emailid, phoneno)
            mycursor.execute(sql, val)

            mydb.commit()
            mydb.close()
            self.successful()
            print("Database Connected Successfully!")
        except:
            # print("Error")
            self.error("Database Connection Failed!")

    def successful(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("The User Data Is Registered Successfully!")
        msg.setStandardButtons(QMessageBox.Save)
        msg.exec_()

    def error(self, message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setText(message)
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
